version: '3.1'

services:
  redis:
    image: redis
    container_name: reveal_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    restart: always
    container_name: reveal_postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: reveal_rabbitmq
    hostname: my-rabbit
    ports:
      - "8080:15672"
      - "5672:5672"
      - "25676:25676"
